version: "2"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file: .env
