<template lang="pug">
v-container(fill-height='' fluid='' grid-list-xl='')
  v-layout(justify-center='' wrap='')
    v-flex(xs12='')
      material-card(color='#2196f3' title='Edit Profile' text='Complete your profile')
        v-form
          v-container(py-0='')
            v-layout(wrap='')
              v-flex(xs12='' md4='')
                v-text-field(label='User Name')
              v-flex(xs12='' md4='')
                v-text-field(label='Email Address')
              v-flex(xs12='' md6='')
                v-text-field(label='First Name')
              v-flex(xs12='' md6='')
                v-text-field(label='Last Name')
              v-flex(xs12='' md12='')
                v-text-field(label='Adress')
              v-flex(xs12='' md4='')
                v-text-field(label='City')
              v-flex(xs12='' md4='')
                v-text-field(label='Country')
              v-flex(xs12='' md4='')
                v-text-field(label='Postal Code' type='number')
              v-flex(xs12='')
                v-textarea(label='About Me' value='Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
              v-flex(xs12='' text-xs-right='')
                v-btn.mx-0.font-weight-light(color='success')
                  | Update Profile
</template>
