<template lang="pug">
v-container(fill-height='' fluid='' grid-list-xl='')
  v-layout(justify-center='' wrap='')
    v-flex(xs12='')
      material-card(color='#2196f3' title='Minha empresa')
        v-form
          v-container(py-0='')
            v-layout(wrap='')
              v-flex(xs12='' md4='')
                v-text-field(label='CNPJ')
              v-flex(xs12='' md4='')
                v-text-field(label='Segmento')
              v-flex(xs12='' md6='')
                v-text-field(label='Razão social')
              v-flex(xs12='' md6='')
                v-text-field(label='Nome fantasia')
              v-flex(xs12='' md12='')
                v-text-field(label='E-mail empresarial')
              v-flex(xs12='' md4='')
                v-text-field(label='Telefone')
              v-flex(xs12='' md4='')
                v-text-field(label='Endereço')
              v-flex(xs12='' md4='')
                v-text-field(label='Quantidade funcionarios')
              v-flex(xs12='' md4='')
                v-text-field(label='Quantidade clientes')
              v-flex(xs12='' md4='')
                v-text-field(label='Porte empresa')
              v-flex(xs12='' md4='')
                v-text-field(label='CNAE')
              v-flex(xs12='' text-xs-right='')
                v-btn.mx-0.font-weight-light(color='#2196f3' style='color: white !important')
                  | Atualizar dados
</template>
